services:
  mongodb:
    image: mongo:7
    container_name: projetapi-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  authapi:
    build: ./authapi
    container_name: authapi-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongo-data:
