spring.application.name=invocationapi
server.port=8083
spring.data.mongodb.uri=mongodb://mongodb:27017/invocationapi
auth.api.url=http://authapi:8080
monster.api.url=http://monsterapi:8082
player.api.url=http://playerapi:8081
